# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Wheeler Games
tagline:          Wheeler Games - making digital versions of your favourite boardgames.
description:      "A two-column black theme with a scrolling sidebar. Ideal for sites requiring a master-detail layout, e.g. documentation, cheatsheets, lyrics, notes..."
url:              https://wheelergames.co.uk/
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Karlo Espiritu
  url:            https://twitter.com/karloespiritu

paginate:         3
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
#  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc

collections:
  games:
    output: true

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
